In [2]:
import tensorflow as tf

sess = tf.Session()
hello = tf.constant('Hello')
print(sess.run(hello))

b'Hello'


In [3]:
a = tf.constant(100)
b = tf.constant(30)

add_op = a + b

sess = tf.Session()
print(sess.run(add_op))

130


In [4]:
a = tf.constant(10)
b = tf.constant(20)
c = tf.constant(30)

mul_op = (a + b) * c

sess = tf.Session()
print(sess.run(mul_op))

900


In [7]:
a = tf.constant(10, name='10')
b = tf.constant(20, name='20')
c = tf.constant(30, name='30')

add_op = tf.add(a, b, name='add')
mul_op = tf.multiply(add_op, c, name='mul')

sess1 = tf.Session()
print(sess1.run(mul_op))

tf.summary.FileWriter('./logs', sess1.graph)

900


In [8]:
v = tf.Variable(0, name='v')

a = tf.constant(10, name='10')
b = tf.constant(20, name='20')

mul_op = tf.multiply(a, b, name='mul')
assign_op = tf.assign(v, mul_op)

sess2 = tf.Session()
sess2.run(assign_op)

tf.summary.FileWriter('./logs', sess2.graph)

print(sess2.run(v))

200


In [9]:
a = tf.placeholder(tf.int32, [5])

two = tf.constant(2)
x2_op = a * two

sess3 = tf.Session()

res1 = sess3.run(x2_op, feed_dict={a: [1, 2, 3, 4, 5]})
print(res1)
res2 = sess3.run(x2_op, feed_dict={a: [5, 6, 7, 10, 100]})
print(res2)

[ 2  4  6  8 10]
[ 10  12  14  20 200]


In [10]:
a = tf.placeholder(tf.int32, [None, 2])

two = tf.constant(2)
x2_op = a * two

sess4 = tf.Session()

sample_list = [[1, 1], [2, 2], [3, 3], [4, 4]]
res = sess4.run(x2_op, feed_dict={a: sample_list})
print(res)

[[2 2]
 [4 4]
 [6 6]
 [8 8]]
